Add files via upload
Protasov-Segey/Python2021-5sem- pull request #1
Opened 2021-09-08 21:14 UTC by Protasov-Segey

2021-09-08 21:23 UTC, Protasov-Segey commented on Дз1.py
> +# In[24]:
Основная программа от 7 до 22 строчки, дальше случайно попали мои доп. тесты в Jupiter'e.

2021-09-08 21:25 UTC, Protasov-Segey commented on Дз1.py
> +
Основная программа с 7 по 22 строчку, дальше находятся мои тесты в Jupiter'e, которые случайно попали в этот файл (в дальнейших задачах буду внимательнее)

2021-09-09 17:16 UTC, Alvant commented on Дз1.py
> +#!/usr/bin/env python
@Protasov-Segey Сергей, по-моему, лучше всё-таки через консоль добавлять файлы (`git add ...`, `git commit ...`, `git push ...`).

Потому что если вы добавляете через Гитхаб сразу, то, получается, в ваш локальный репозиторий (который папка на компьютере) файл не добавляется? То есть файл лежит в папке, но не в Гите, который в папке? 😅 То есть получается рассинхрон между Гитхабом и локальным репозиторием, из-за чего потом мб могут какие-то "грабли" появляться.

Ещё так не стоит делать (заливать сразу через Гитхаб) потому, что... это как бы идёт немного поперёк самой идеологии использования Гита. Пайплайн в идеале должен быть такой: вы локально работаете, пишите код, коммитите (небольшая осмысленная часть работы = коммит). И как готово, пушите на сервер. (Либо пушите просто так через какие-то временные промежутки, чтоб код не только локально существовал, то есть пуш — как мера backup-а). Получается, локально коммитить — это вроде как часть пайплайна)

Ещё при заливке сразу через Гитхаб получилось так, что у вас в заголовке реквеста и в сообщении коммита стоит неинформативная строчка "Add files via upload" 🙃

2021-09-09 17:21 UTC, Alvant commented on Дз1.py
> +#!/usr/bin/env python
Имя файла на русском. 🤔 Думаю, для файлов с кодом лучше на английском писать название. Хотя бы потому, что вам может понадобиться импортировать некоторые функции из одного своего файла в другой (если задание более сложное и файлов несколько), и тогда надо будет делать импорт из модуля с русским именем (хз, захочет ли Питон так делать). То есть имя файла — это как "часть кода программы" (который на английском)

2021-09-09 17:22 UTC, Alvant commented on Дз1.py
> +# In[31]:
Ненужный коммент (видимо, остался при копировании из ноутбука?)

2021-09-09 17:27 UTC, Alvant commented on Дз1.py
> +
Да в тестах нет ничего плохого) Наоборот, если есть тесты, то это даже лучше. Но если они есть, они должны быть рабочими. А сейчас получилось так, что у вас не совсем тест, а... да, просто часть кода, случайно скопированного из ноутбука: `if s[i+1] != ' '` без двоеточия и блока под if (нерабочий код), строчка `18 5 11 20 12 32 17 9 8 0 23 9 32 End` (нерабочий код).

В общем, мне кажется, что надо либо оставить основную программу (убрав тесты). Либо нормально оформить эти тесты, чтоб они не ломали программу) (попробуйте запустить `python Дз1.py` — наверняка будет ошибка)

2021-09-09 17:29 UTC, Alvant commented on Дз1.py
> +    number = int(number)
По-моему, код был бы более читаемый, если конструкции типа if и while ещё пустыми строчками отделять. То есть
```python
number = input()
string = ''

if number == 'End' :
    print()
else : 
    number = int(number)

while number != 'End' :
    number = int(number)
```

2021-09-09 17:32 UTC, Alvant commented on Дз1.py
> +    elif number >= 0 and (number <= 5) :
Лишние скобки и лишний пробел перед двоеточием `(number <= 5) :`

А что за странная проверка?) Сюда бы стоило вставить поясняющий комментарий хотя бы. Потому что не очевидно имхо

2021-09-09 17:42 UTC, Alvant commented on Дз1.py
> +    elif number >= 0 and (number <= 5) :
Ок. Я вроде понял. Но ведь вы так букву `ё` потеряли?) Давайте сохраним её?)

Мне кажется, что для решения этого задания можно бы было просто создать словарик: индекс -> буква. И просто из этого словарика доставать по индексу нужную букву в цикле. Это и просто, и понятно всё, и буква `ё` сохраняется)

2021-09-09 17:47 UTC, Alvant requested changes
Ок! В целом норм. Но сможете плиз пару вещей ещё поправить?

* Имя файла сделать на английском
* Убрать тесты из Юпитера, которые сейчас в конце файла (чтоб не было ошибок при `python Дз1.py`)
* Вместо подхода "`chr(1072 +`" (с пропуском буквы `ё`) давайте вы просто через руками составленный словарик "индекс -> буква" попробуете задачу решить? По-моему, такой вариант намного лучше?

2021-09-10 16:17 UTC, merged