My homework
Protasov-Segey/Python2021-5sem- pull request #2
Opened 2021-09-13 22:09 UTC by Protasov-Segey

2021-09-14 07:41 UTC, Alvant commented on Homework1.py
> +# In[2]:
Лишний коммент

2021-09-14 07:41 UTC, Alvant commented on Homework1.py
> +# In[ ]:
Тоже лишний коммент (и много пустых строчек)

2021-09-14 07:42 UTC, Alvant commented on Homework1.py
> +if number == 'End' :
Мне кажется, этот блок if-else лишний (он только "внимание отвлекает", но ничего полезного вроде не делает)

2021-09-14 07:44 UTC, Alvant commented on Homework1.py
> +       'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', ' ']#Создал список букв+пробел
Ок, прикольно) вы обошлись без словаря, используя только список + питонскую фишку, что индекс -1 соответствует последнему элементу.

P.S. Коммент лучше через пробел писать от кода, или лучше даже через два пробела, не вплотную:
```python
'ю', 'я', ' ']  # Создал список букв+пробел
```

2021-09-14 07:46 UTC, Alvant commented on Homework1.py
> +while number != 'End' :
Двоеточие лучше без пробела писать:
```python
while number != 'End':
```

2021-09-14 07:47 UTC, Alvant commented on Homework1.py
> +    number = input()
Не очень хорошо, что переменная называется `number`, хотя она половину времени "своей жизни" является строкой, а не числом. Плюс она ещё может быть словом End, которое уж точно не number)

2021-09-14 07:50 UTC, Alvant commented on Homework1.py
> +buf = ['а', 'б', 'в', 'г', 'д', 'е', 'ё', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о',
Мне кажется, имя `buf` не очень удачное. Лучше бы было alphabet, например, или knows_symbols, или ordered_chars, или ещё как) Buf — это как временное хранилище для чего-то... А тут вы задаёте словарь + ещё и отображение между индексами и буквами сразу. Ещё это можно бы было даже в верхнем регистре назвать, типа константа `ALPHABET= ['a', ...`

2021-09-14 07:51 UTC, Alvant commented on Homework1.py
> +    print()
Кстати, если на вход поступает сразу строка End, то ваша программа выведет две пустых строки, вместо одной (вот тут плюс ещё в самом конце есть print)

2021-09-14 07:54 UTC, Alvant approved these changes

2021-09-14 19:33 UTC, Alvant commented on Homework1.py
> +# coding: utf-8
Я тоже на знаю 😅 Но с этим ещё ничего: он говорит, чем надо запускать код + указывает кодировку. А вот комменты `# In[2]:` — это уже лишнее совсем. Это бы надо было руками просто убрать из файла.

2021-09-16 20:58 UTC, Alvant commented on Homework2
> +#!/bin/bash
Файлу скрипта лучше бы было дать расширение .sh

2021-09-16 21:02 UTC, Alvant commented on Homework2
> +ls -l | grep "^d" | wc  -l >> info.txt
`ls -l | grep "^d"` Ок! Но таким образом вы не увидите скрытые папки (имена которых начинаются с точки)...
```bash
directory
.secret_directory
```

2021-09-16 21:03 UTC, Alvant commented on Homework2
> +ls -l | grep "^d" | wc  -l >> info.txt
Два пробела после wc и перед -l (можно было одним обойтись :upside_down_face:)

2021-09-16 21:13 UTC, Alvant requested changes
@Protasov-Segey По второму ДЗ всё в целом ОК. Единственное, что стоит поправить — подсчёт папок. Сейчас скрытые папки не учитываются. Ну, ещё файл лучше бы переименовать, чтоб было расширение .sh)

А, да, ещё надо поправить последние две команды так, чтоб они именно в домашней папке поиск проводили. (Сейчас они ищут там, откуда запущен скрипт)

2021-09-20 16:34 UTC, Alvant commented on Homework2.sh
> +cd /home
Нет) домашняя — это `~`. А конкретное значение `~` уже будет своё у каждого пользователя, кто бы ни запустил скрипт.

2021-09-20 16:38 UTC, Alvant commented on Homework2.sh
> +#!/bin/bash
Надо было правки внести в самый первый файл Homework. Вы добавили новый файл. Просто если смёржить реквест, то оба файла (и старый, и новый) окажутся в репозитории (это не совсем ОК).

Ещё если бы во поправили исходный файл, то Гит запомнил бы историю изменений этого файла, и вы при желании всё равно могли бы откатиться к старой версии решения.

Короче, сейчас надо бы, например, просто убрать старый файл Homework2 (старая версия решения потеряется, ну и ладно). Но в следующий раз надо прям в тот же файл правки вносить.

2021-09-20 16:43 UTC, Alvant commented on Homework2.sh
> +ls -la | grep ^d | wc  -l >> info.txt
Да, но теперь вы посчитали всё, и скрытое, и нет. Но также захватили две лишние "папки")
```bash
$ ls -al
drw-rw-rw-  43 Василий 0    32768 2021-09-17 01:41 ./
dr--r--r--  12 Василий 0     4096 2020-03-27 15:36 ../
...
```
В выводе `ls -al` есть также `.` — это текущая папка, и `..` — это родительская папка. Кажется, что их уже не надо учитывать?) при подсчёте количества папок.

2021-09-20 16:45 UTC, Alvant requested changes
Ок. Но теперь надо бы убрать лишний файл (со старой версией скрипта). И команда для подсчёта числа папок всё равно говорит пока немного не то 🙂 (значение, которое записывается сейчас в info.txt, на 2 больше того, которое должно бы было быть)

2021-09-20 16:49 UTC, Alvant commented
P.S. Вот в этой вкладке реквеста можно посмотреть, какие файлы добавляются/изменяются по сравнению с main. Видно, что тут два Homework2 (с и без .sh)
![Снимок экрана (6988)](https://user-images.githubusercontent.com/15067981/134041724-6d1f304d-d23a-499c-bed3-574496467f8d.png)

2021-09-20 17:59 UTC, Protasov-Segey commented on Homework2.sh
> +ls -la | grep ^d | wc  -l >> info.txt
Так они же тоже как бы скрытые) Тут всё зависит от формулировки задачи уже)

2021-09-20 20:24 UTC, Alvant commented on Homework2.sh
> +ls -la | grep ^d | wc  -l >> info.txt
@Protasov-Segey ну, как бы да, но вообще нет)

...
...А хотя 🤔
...Пожалуй... да, согласен)

Ок, со скриптом всё норм. Но один файл в реквесте всё равно лишний)

2021-09-28 13:48 UTC, Alvant commented on Homework2.sh
> +cd /home
Эх, надо бы было ещё тут поправить, папку нужную указать. Ну ладно)

2021-09-28 13:48 UTC, Alvant approved these changes

2021-10-08 15:12 UTC, merged